app:
  scheduler:
    enable: true
    interval: 100s
    force-check-delay: 50s
  database-access-type: jpa
  github-client:
    base-url: https://api.github.com
    retry:
      max-attempts: 3
      max-interval: 100ms
      strategy: constant
      retry-codes:
        - 500
        - 502
        - 503
  stack-overflow-client:
    base-url: https://api.stackexchange.com
    retry:
      max-attempts: 3
      max-interval: 2s
      strategy: constant
      retry-codes:
        - 500
        - 502
        - 503
  bot-client:
    base-url: http://localhost:8090
    retry:
      max-attempts: 3
      max-interval: 100ms
      strategy: constant
      retry-codes:
        - 500
        - 502
        - 503


spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:log4j2-plain.xml
