app:
  scheduler:
    enable: true
    interval: 100s
    force-check-delay: 50s
  database-access-type: jpa
  use-queue: true
  github-client:
    base-url: https://api.github.com
    retry:
      max-attempts: 3
      max-interval: 100ms
      strategy: exponential
      retry-codes:
        - 500
        - 502
        - 503
  stack-overflow-client:
    base-url: https://api.stackexchange.com
    retry:
      max-attempts: 3
      max-interval: 100ms
      strategy: exponential
      retry-codes:
        - 500
        - 502
        - 503
  bot-client:
    base-url: http://localhost:8090
    retry:
      max-attempts: 3
      max-interval: 1s
      strategy: constant
      retry-codes:
        - 500
        - 502
        - 503
  kafka-producer:
    bootstrap-servers: localhost:29092
    acks: all
    topic-name: updates

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  #cache:
    #jcache:
      #provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    #cache-names:
     # - scrapper-buckets
    #caffeine:
     # spec: maximumSize=100000,expireAfterAccess=3600s

#bucket4j:
 # enabled: true
  #filters:
   # - cache-name: scrapper-buckets
    #  url: .*
     # http-status-code: TOO_MANY_REQUESTS
      #http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\":
      #\"You have exhausted your API Request Quota\" }"
      #rate-limits:
       # - cache-key: getRemoteAddr()
        #  bandwidths:
         #   - capacity: 50
          #    refill-capacity: 1
           #   time: 2
            #  unit: seconds
             # initial-capacity: 10
              #refill-speed: interval

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:log4j2-plain.xml
