/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.model.jooq.tables;

import edu.java.domain.model.jooq.DefaultSchema;
import edu.java.domain.model.jooq.Keys;
import edu.java.domain.model.jooq.tables.records.TrackingsRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Trackings extends TableImpl<TrackingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TRACKINGS</code>
     */
    public static final Trackings TRACKINGS = new Trackings();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<TrackingsRecord> getRecordType() {
        return TrackingsRecord.class;
    }

    /**
     * The column <code>TRACKINGS.CHAT_ID</code>.
     */
    public final TableField<TrackingsRecord, Long> CHAT_ID =
        createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>TRACKINGS.LINK_ID</code>.
     */
    public final TableField<TrackingsRecord, Long> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private Trackings(Name alias, Table<TrackingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Trackings(Name alias, Table<TrackingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>TRACKINGS</code> table reference
     */
    public Trackings(String alias) {
        this(DSL.name(alias), TRACKINGS);
    }

    /**
     * Create an aliased <code>TRACKINGS</code> table reference
     */
    public Trackings(Name alias) {
        this(alias, TRACKINGS);
    }

    /**
     * Create a <code>TRACKINGS</code> table reference
     */
    public Trackings() {
        this(DSL.name("TRACKINGS"), null);
    }

    public <O extends Record> Trackings(Table<O> child, ForeignKey<O, TrackingsRecord> key) {
        super(child, key, TRACKINGS);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<TrackingsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D1A;
    }

    @Override
    @NotNull
    public List<ForeignKey<TrackingsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_D, Keys.CONSTRAINT_D1);
    }

    private transient Chats _chats;
    private transient Links _links;

    /**
     * Get the implicit join path to the <code>PUBLIC.CHATS</code> table.
     */
    public Chats chats() {
        if (_chats == null) {
            _chats = new Chats(this, Keys.CONSTRAINT_D);
        }

        return _chats;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null) {
            _links = new Links(this, Keys.CONSTRAINT_D1);
        }

        return _links;
    }

    @Override
    @NotNull
    public Trackings as(String alias) {
        return new Trackings(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Trackings as(Name alias) {
        return new Trackings(alias, this);
    }

    @Override
    @NotNull
    public Trackings as(Table<?> alias) {
        return new Trackings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Trackings rename(String name) {
        return new Trackings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Trackings rename(Name name) {
        return new Trackings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Trackings rename(Table<?> name) {
        return new Trackings(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
