/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.model.jooq;

import edu.java.domain.model.jooq.tables.Chats;
import edu.java.domain.model.jooq.tables.Links;
import edu.java.domain.model.jooq.tables.Trackings;
import edu.java.domain.model.jooq.tables.records.ChatsRecord;
import edu.java.domain.model.jooq.tables.records.LinksRecord;
import edu.java.domain.model.jooq.tables.records.TrackingsRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatsRecord> CONSTRAINT_3 =
        Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3"), new TableField[] {Chats.CHATS.CHAT_ID}, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_4 =
        Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] {Links.LINKS.LINK_ID}, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_45 =
        Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] {Links.LINKS.URL}, true);
    public static final UniqueKey<TrackingsRecord> CONSTRAINT_D1A = Internal.createUniqueKey(Trackings.TRACKINGS,
        DSL.name("CONSTRAINT_D1A"),
        new TableField[] {Trackings.TRACKINGS.LINK_ID, Trackings.TRACKINGS.CHAT_ID},
        true
    );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TrackingsRecord, ChatsRecord> CONSTRAINT_D =
        Internal.createForeignKey(Trackings.TRACKINGS,
            DSL.name("CONSTRAINT_D"),
            new TableField[] {Trackings.TRACKINGS.CHAT_ID},
            Keys.CONSTRAINT_3,
            new TableField[] {Chats.CHATS.CHAT_ID},
            true
        );
    public static final ForeignKey<TrackingsRecord, LinksRecord> CONSTRAINT_D1 =
        Internal.createForeignKey(Trackings.TRACKINGS,
            DSL.name("CONSTRAINT_D1"),
            new TableField[] {Trackings.TRACKINGS.LINK_ID},
            Keys.CONSTRAINT_4,
            new TableField[] {Links.LINKS.LINK_ID},
            true
        );
}
