/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.model.jooq;

import edu.java.domain.model.jooq.tables.Chats;
import edu.java.domain.model.jooq.tables.Links;
import edu.java.domain.model.jooq.tables.Trackings;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>CHATS</code>.
     */
    public static final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>LINKS</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>TRACKINGS</code>.
     */
    public static final Trackings TRACKINGS = Trackings.TRACKINGS;
}
